# Note about DNS:
#   using DOCKER_HOST results in the host getting the wrong DNS
#   configuration, so we use known good public nameservers
#   instead of the misconfigured ones

services:
  autoheal:
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4

  nginx:
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ${WORKSPACE_ROOT:?error}/nginx/docker-entrypoint.d/50-hot-reload.sh:/docker-entrypoint.d/50-hot-reload.sh:ro
      - ${WORKSPACE_ROOT:?error}/nginx/conf.d/custom:/etc/nginx/conf.d/custom:ro
      - ${WORKSPACE_ROOT:?error}/nginx/templates:/etc/nginx/templates:ro
      - ${WORKSPACE_ROOT:?error}/letsencrypt:/etc/letsencrypt:ro

  certbot:
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ${WORKSPACE_ROOT:?error}/letsencrypt:/etc/letsencrypt
      - ${WORKSPACE_ROOT:?error}/certbot/certbot_sa_key.json:/root/.config/gcloud/application_default_credentials.json:ro
      
  homelink:
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ${WORKSPACE_ROOT:?error}/homelink/homelink_sa_key.json:/root/.config/gcloud/application_default_credentials.json:ro

  actual:
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ${WORKSPACE_ROOT:?error}/actual/data:/data

  jellyfin:
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - JELLYFIN_PublishedServerUrl=https://media.lymer.ca
    volumes:
      - ${WORKSPACE_ROOT:?error}/jellyfin/config:/config
      - ${WORKSPACE_ROOT:?error}/jellyfin/cache:/cache
      - /mnt/main/music:/media/music:ro
      - /mnt/main/torrents:/media/torrents:ro

  transmission:
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
    - /mnt/main/torrents:/data:rw
    - ${WORKSPACE_ROOT:?error}/transmission/scripts:/scripts:ro
