# Note about DNS:
#   using DOCKER_HOST results in the host getting the wrong DNS
#   configuration, so we use known good public nameservers
#   instead of the misconfigured ones

services:
  autoheal:
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4

  nginx:
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /share/homes/qnappy/homelab/nginx/docker-entrypoint.d/50-hot-reload.sh:/docker-entrypoint.d/50-hot-reload.sh:ro
      - /share/homes/qnappy/homelab/nginx/conf.d/custom:/etc/nginx/conf.d/custom:ro
      - /share/homes/qnappy/homelab/nginx/templates:/etc/nginx/templates:ro
      - /share/homes/qnappy/homelab/letsencrypt:/etc/letsencrypt:ro

  certbot:
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /share/homes/qnappy/homelab/letsencrypt:/etc/letsencrypt
      - /share/homes/qnappy/homelab/certbot/certbot_sa_key.json:/root/.config/gcloud/application_default_credentials.json:ro
      
  homelink:
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /share/homes/qnappy/homelab/homelink/homelink_sa_key.json:/root/.config/gcloud/application_default_credentials.json:ro

  actual:
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /share/homes/qnappy/homelab/actual/data:/data

  jellyfin:
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - JELLYFIN_PublishedServerUrl=https://media.lymer.ca
    volumes:
      - /share/homes/qnappy/homelab/jellyfin/config:/config
      - /share/homes/qnappy/homelab/jellyfin/cache:/cache
      - /share/Music:/media/music:ro
      - /share/Torrents/completed:/media/torrents:ro
