---
version: "3"
services:
  autoheal:
    image: willfarrell/autoheal:1.2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    image: nginx:mainline-alpine
    ports:
      - 13448:443
      - 10808:80
    environment:
      - "NGINX_SSL_CERTIFICATE=/etc/letsencrypt/live/lymer.ca/fullchain.pem"
      - "NGINX_SSL_CERTIFICATE_KEY=/etc/letsencrypt/live/lymer.ca/privkey.pem"
    volumes:
      - ./workloads/nginx/docker-entrypoint.d/50-hot-reload.sh:/docker-entrypoint.d/50-hot-reload.sh:ro
      - ./workloads/nginx/conf.d/custom:/etc/nginx/conf.d/custom:ro
      - ./workloads/nginx/templates:/etc/nginx/templates:ro
      - ./docker/data/etc/letsencrypt:/etc/letsencrypt:ro
    labels:
      - "autoheal=true"
    healthcheck:
      test: ["CMD", "curl", "https://status.lymer.ca/", "--fail", "--resolve", "status.lymer.ca:443:127.0.0.1"]
      interval: 30s
      timeout: 10s
      retries: 3

  certbot:
    image: certbot/dns-google
    volumes:
      - ./docker/data/etc/letsencrypt/:/etc/letsencrypt
      - ~/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json:ro
    entrypoint:
      - sh
      - -c
      - |
        trap exit INT TERM
        while true; do
          certbot certonly \
            --agree-tos \
            --noninteractive \
            --preferred-challenges dns \
            --domain "*.lymer.ca" \
            --dns-google \
            --dns-google-project matthewlymer-production
          sleep 12h
        done &
        wait

  homelink:
    build:
      context: workloads/homelink
      dockerfile: ./Dockerfile
    volumes:
      - ~/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json:ro
    environment:
      - "CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE=/root/.config/gcloud/application_default_credentials.json"
      - "GOOGLE_PROJECT=matthewlymer-production"
      - "DNS_NAME=*.lymer.ca."
      - "ZONE=lymer-ca"
    entrypoint:
      - sh
      - -c
      - |
        trap exit INT TERM
        while true; do
          ./update-dns-records.sh
          sleep 15m
        done &
        wait

  actual:
    labels:
      - "autoheal=true"
    image: actualbudget/actual-server:sha-3cab9a3-alpine # May 11, 2025 at 8:57 pm
    volumes:
      - ./workloads/actual/data:/data
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:5006/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  jellyfin:
    labels:
      - "autoheal=true"
    image: jellyfin/jellyfin
    volumes:
      - ./workloads/jellyfin/data/config:/config
      - ./workloads/jellyfin/data/cache:/cache
      - ./workloads/jellyfin/data/media/music:/media/music:ro
      - ./workloads/jellyfin/data/media/torrents:/media/torrents:ro

  transmission:
    labels:
      - "autoheal=true"
    image: haugene/transmission-openvpn:3.7
    cap_add:
      - NET_ADMIN
    ports:
      - 9091:9091
    environment:
      - LOCAL_NETWORK=192.168.0.0/16
      - OPENVPN_PROVIDER=TORGUARD
      - OPENVPN_CONFIG=Mexico
      - OPENVPN_USERNAME=${TRANSMISSION_OPENVPN_USERNAME:-}
      - OPENVPN_PASSWORD=${TRANSMISSION_OPENVPN_PASSWORD:-}
    volumes:
      - ./workloads/transmission/data:/data:rw
      - ./workloads/transmission/scripts:/scripts:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
