server {
    listen 80;
    return 302 https://$host$request_uri;
}

server {
    include /etc/nginx/conf.d/setup-ssl.inc;

    server_name default;

    return 404;
}

server {
    include /etc/nginx/conf.d/setup-ssl.inc;

    server_name status.*;

    default_type text/plain;

    add_header Cache-Control "no-store";

    return 200 "OK";
}

server {
    include /etc/nginx/conf.d/setup-ssl.inc;

    server_name auth.*;

    resolver 127.0.0.11;
    set $target "http://oauth2-proxy:4180";

    location / {
        proxy_pass $target;
    }
}

server {
    include /etc/nginx/conf.d/setup-ssl.inc;

    server_name budget.*;

    resolver 127.0.0.11;
    set $target "http://actual:5006";

    location / {
        proxy_pass $target;
    }
}

server {
    include /etc/nginx/conf.d/setup-ssl.inc;

    server_name media.*;

    resolver 127.0.0.11;
    set $target "http://jellyfin:8096";

    location / {
        proxy_pass $target;
    }
}

server {
    include /etc/nginx/conf.d/setup-ssl.inc;

    server_name prowlarr.*;

    resolver 127.0.0.11;
    set $target "http://prowlarr:9696";

    location / {
        auth_request /internal-oauth2-auth;
        error_page 401 = @error401;

        proxy_pass $target;
    }

    include /etc/nginx/conf.d/auth-routes.inc;
}

server {
    include /etc/nginx/conf.d/setup-ssl.inc;

    server_name sonarr.*;

    resolver 127.0.0.11;
    set $target "http://sonarr:8989";

    location / {
        auth_request /internal-oauth2-auth;
        error_page 401 = @error401;

        proxy_pass $target;
    }

    include /etc/nginx/conf.d/auth-routes.inc;
}

server {
    include /etc/nginx/conf.d/setup-ssl.inc;

    server_name transmission.*;

    resolver 127.0.0.11;
    set $target "http://transmission:9091";

    location / {
        auth_request /internal-oauth2-auth;
        error_page 401 = @error401;

        proxy_pass $target;
    }

    include /etc/nginx/conf.d/auth-routes.inc;
}
